---
title: "Leaf Color Change Date in Harvard Forest"
author: "Kevin Buck, Kyle Elliott, Sydney Higgins"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#plotting
library(ggplot2)
# data manipulation
library(tidyverse)
# making residual plots
library(ggResidpanel)
# estimating marginal means
library(emmeans)
# needed for creating proper ANOVA table
library(car)
#Anova stat package
library(rstatix)
library(ggpubr)
```

####Introduction####
mini Literature review of phenological shift trends
establish the question
establish what dataset we are doing

#### Analysis####
Data visualization
```{r}
pheno <- read.csv(file="hf003-08-fall-mean-spp.csv") #read in the data
pheno_trimmed <- pheno %>% #pipe in data
  #filter in species present for the whole dataset
  filter(species=="ACRU"|species=="ACSA"|species=="ACPE"|species=="AMSP"|
           species=="BEAL"|species=="BELE"|species=="BEPA"|species=="FAGR"|
           species=="FRAM"|species=="NYSY"|species=="PRSE"|species=="QUAL"|
           species=="QURU"|species=="QUVE")
pheno_trimmed %>% 
  ggplot(aes(x = year, y = lc_doy)) + #set year as x axis and julian day of change as the y
  geom_point(aes(color=species, fill=species), size=2) + 
  ggtitle("Leaf Color Change Date Over Time")+ #add title
  xlab("Year") + #label x axis
  ylab("Date 50% of Leaves Changed Color ") + #label y axis
  theme_classic() #changing background
```
ANCOVA
```{r}
options(contrasts = c("contr.sum","contr.ply")) #options fo later post hoc comparison
model_1 <- lm(lc_doy ~ year * species,data=pheno_trimmed) #build linear model
summary(model_1) #view linear model
resid_panel(model_1,plot="all") #check on residuals
Anova(model_1, type = 3) #run an ANCOVA
pwc <- pheno_trimmed %>% tukey_hsd(lc_doy ~ species) #pair wise comparisons
pwc #look at the PWC of species
```

